# This file generated by Quarto; do not edit by hand.
# shiny_mode: core

from __future__ import annotations

from pathlib import Path
from shiny import App, Inputs, Outputs, Session, ui

import pandas as pd
import numpy as np
import plotly.graph_objects as go
import plotly.express as px
from plotly.subplots import make_subplots
from shiny import reactive

# ── Constantes ────────────────────────────────────────────────────
COLORS = {"POSITIVA": "#2ecc71", "NEUTRA": "#95a5a6", "NEGATIVA": "#e74c3c"}
TIER_WEIGHTS = {"Muito Relevante": 8, "Relevante": 4, "Menos Relevante": 1, "Null": 1}
TIER_ORDER = ["Muito Relevante", "Relevante", "Menos Relevante", "Null"]
TIER_EMOJI = {"Muito Relevante": "🔴", "Relevante": "🟠", "Menos Relevante": "🔵", "Null": "⚪"}
NSS_SCALE = [[0,"#c0392b"],[0.3,"#e74c3c"],[0.5,"#fdfefe"],[0.7,"#82e0aa"],[1,"#1e8449"]]

def nss(df):
    ds = df[df["Classificação"] != "PUBLICIDADE"]
    n = len(ds)
    if n == 0: return 0.0
    return ((ds["Classificação"]=="POSITIVA").sum() - (ds["Classificação"]=="NEGATIVA").sum()) / n * 100

def nss_w(df):
    ds = df[df["Classificação"] != "PUBLICIDADE"]
    if len(ds) == 0: return 0.0
    w = ds["Peso"].sum()
    return (ds.loc[ds["Classificação"]=="POSITIVA","Peso"].sum() - ds.loc[ds["Classificação"]=="NEGATIVA","Peso"].sum()) / w * 100

# ── Carregar dados ────────────────────────────────────────────────
url = "https://docs.google.com/spreadsheets/d/1UVGM5g7A2pSmg4Nn5eTzjZhd25sAFFDbkBclRfyNgX8/export?format=csv"
df_raw = pd.read_csv(url)
df_raw["Data"] = pd.to_datetime(df_raw["Data"], dayfirst=True, format="mixed", errors="coerce")
df_raw = df_raw.dropna(subset=["Data"]).sort_values("Data")
df_raw["Ano_Mes"] = df_raw["Data"].dt.to_period("M").astype(str)
df_raw["Peso"] = df_raw["Tier"].map(TIER_WEIGHTS).fillna(1)
df_raw["Tier"] = df_raw["Tier"].fillna("Null")

# ========================================================================




def server(input: Inputs, output: Outputs, session: Session) -> None:
    from shiny import ui

    ui.input_selectize("sel_grupo", "Grupo", 
        choices=["Todos"] + sorted(df_raw["Grupo"].dropna().unique().tolist()),
        selected="Todos")

    ui.input_selectize("sel_tier", "Tier", 
        choices=["Todos"] + TIER_ORDER,
        selected="Todos", multiple=True)

    ui.input_selectize("sel_midia", "Mídia",
        choices=["Todos"] + sorted(df_raw["Mídia"].dropna().unique().tolist()),
        selected="Todos")

    ui.input_selectize("sel_cat", "Categoria",
        choices=["Todos"] + sorted(df_raw["Categoria"].dropna().unique().tolist()),
        selected="Todos", multiple=True)

    ui.input_slider("min_vol", "Volume mínimo (veículos)", min=1, max=50, value=5)

    ui.hr()
    ui.markdown("**Sobre os pesos (Tier):**")
    ui.markdown("🔴 Muito Relevante = 8×")
    ui.markdown("🟠 Relevante = 4×")  
    ui.markdown("🔵 Menos Relevante = 1×")
    ui.markdown("⚪ Null = 1×")

    # ========================================================================

    @reactive.calc
    def filtered():
        df = df_raw.copy()
        if input.sel_grupo() != "Todos":
            df = df[df["Grupo"] == input.sel_grupo()]
        sel_t = input.sel_tier()
        if sel_t and "Todos" not in sel_t:
            df = df[df["Tier"].isin(sel_t)]
        if input.sel_midia() != "Todos":
            df = df[df["Mídia"] == input.sel_midia()]
        sel_c = input.sel_cat()
        if sel_c and "Todos" not in sel_c:
            df = df[df["Categoria"].isin(sel_c)]
        return df

    @reactive.calc
    def sent():
        return filtered()[filtered()["Classificação"] != "PUBLICIDADE"]

    # ========================================================================

    from shiny.render import text
    @text
    def kpi_nss():
        return f"{nss(filtered()):+.1f}"

    # ========================================================================

    @text
    def kpi_nssw():
        return f"{nss_w(filtered()):+.1f}"

    # ========================================================================

    @text
    def kpi_total():
        return f"{len(sent()):,}"

    # ========================================================================

    @text
    def kpi_periodo():
        df = filtered()
        if len(df) == 0: return "—"
        return f"{df['Data'].min().strftime('%b/%Y')} a {df['Data'].max().strftime('%b/%Y')}"

    # ========================================================================

    from shinywidgets import render_plotly

    @render_plotly
    def fig_sentimento():
        ds = sent()
        if len(ds) == 0: return go.Figure()
        counts = ds["Classificação"].value_counts()
        fig = go.Figure(go.Pie(
            labels=counts.index, values=counts.values, hole=0.45,
            marker_colors=[COLORS.get(c,"#ccc") for c in counts.index],
            textinfo="percent+label",
        ))
        fig.update_layout(height=380, showlegend=False, margin=dict(l=10,r=10,t=10,b=10))
        return fig

    # ========================================================================

    @render_plotly
    def fig_categorias():
        ds = sent()
        if len(ds) == 0: return go.Figure()
        cats = ds["Categoria"].value_counts().head(12).index
        rows = []
        for c in cats:
            dc = ds[ds["Categoria"]==c]
            p = (dc["Classificação"]=="POSITIVA").sum()
            n_ = (dc["Classificação"]=="NEGATIVA").sum()
            rows.append({"Categoria":c, "N":len(dc), "NSS":round((p-n_)/len(dc)*100,1)})
        cdf = pd.DataFrame(rows).sort_values("NSS")
        fig = go.Figure(go.Bar(
            x=cdf["NSS"], y=cdf["Categoria"], orientation="h",
            marker_color=[COLORS["NEGATIVA"] if x<0 else COLORS["POSITIVA"] for x in cdf["NSS"]],
            text=[f"{x:+.1f}" for x in cdf["NSS"]], textposition="outside",
        ))
        fig.add_vline(x=0, line_color="black", line_width=1)
        fig.update_layout(height=380, template="plotly_white", margin=dict(l=10,r=60,t=10,b=30))
        return fig

    # ========================================================================

    @render_plotly
    def fig_temporal():
        ds = sent()
        if len(ds) == 0: return go.Figure()
        rows = []
        for m in sorted(ds["Ano_Mes"].unique()):
            dm = ds[ds["Ano_Mes"]==m]
            rows.append({"Mês":m, "Simples":nss(dm), "Ponderado":nss_w(dm), "N":len(dm)})
        ndf = pd.DataFrame(rows)
        fig = go.Figure()
        fig.add_trace(go.Scatter(x=ndf["Mês"],y=ndf["Simples"],mode="lines+markers",name="NSS Simples",line=dict(color=COLORS["POSITIVA"],width=3)))
        fig.add_trace(go.Scatter(x=ndf["Mês"],y=ndf["Ponderado"],mode="lines+markers",name="NSS Ponderado",line=dict(color=COLORS["NEGATIVA"],width=3,dash="dash"),marker=dict(symbol="diamond")))
        fig.add_hline(y=0,line_dash="dot",line_color="gray",opacity=0.5)
        fig.update_layout(height=400,template="plotly_white",hovermode="x unified",legend=dict(orientation="h",y=-0.15,x=0.5,xanchor="center"))
        return fig

    # ========================================================================

    @render_plotly
    def fig_scatter():
        ds = sent()
        if len(ds) == 0: return go.Figure()
        mn = input.min_vol()
        prof = ds.groupby("Veículo_de_comunicacao").agg(
            Total=("Classificação","count"),
            Pos=("Classificação",lambda x:(x=="POSITIVA").sum()),
            Neg=("Classificação",lambda x:(x=="NEGATIVA").sum()),
        )
        prof = prof[prof["Total"]>=mn].copy()
        prof["NSS"] = ((prof["Pos"]-prof["Neg"])/prof["Total"]*100).round(1)
        prof = prof.reset_index()
        if len(prof)==0: return go.Figure()
        fig = go.Figure(go.Scatter(
            x=prof["Total"],y=prof["NSS"],mode="markers",
            marker=dict(size=12,color=prof["NSS"],colorscale=NSS_SCALE,cmid=0,showscale=True,line=dict(width=1,color="#2c3e50")),
            text=prof["Veículo_de_comunicacao"],
            hovertemplate="<b>%{text}</b><br>Volume: %{x}<br>NSS: %{y:+.1f}<extra></extra>",
        ))
        fig.add_hline(y=0,line_dash="dash",line_color="#34495e")
        fig.update_layout(height=500,template="plotly_white",xaxis=dict(title="Volume",type="log"),yaxis_title="NSS")
        return fig

    # ========================================================================

    @render_plotly
    def fig_heatmap():
        ds = sent()
        if len(ds) == 0: return go.Figure()
        top_cats = ds["Categoria"].value_counts().head(10).index.tolist()
        dw = ds[ds["Categoria"].isin(top_cats)]
        results = []
        for cat in top_cats:
            for mes in sorted(dw["Ano_Mes"].unique()):
                s = dw[(dw["Categoria"]==cat)&(dw["Ano_Mes"]==mes)]
                n = len(s)
                v = round((s["Classificação"].eq("POSITIVA").sum()-s["Classificação"].eq("NEGATIVA").sum())/n*100,1) if n>=3 else np.nan
                results.append({"Categoria":cat,"Mês":mes,"NSS":v})
        hp = pd.DataFrame(results).pivot(index="Categoria",columns="Mês",values="NSS").reindex(top_cats)
        fig = go.Figure(go.Heatmap(
            z=hp.values,x=hp.columns.tolist(),y=hp.index.tolist(),
            colorscale=NSS_SCALE,zmid=0,text=hp.values.round(0),texttemplate="%{text:+.0f}",
            colorbar=dict(title="NSS"),
        ))
        fig.update_layout(height=max(400,len(top_cats)*40),template="plotly_white",yaxis=dict(autorange="reversed"),margin=dict(l=180))
        return fig

    # ========================================================================

    @render_plotly
    def fig_treemap():
        ds = sent()
        if len(ds) == 0: return go.Figure()
        tm = ds.groupby(["Tier","Categoria"]).agg(
            Total=("Classificação","count"),
            Pos=("Classificação",lambda x:(x=="POSITIVA").sum()),
            Neg=("Classificação",lambda x:(x=="NEGATIVA").sum()),
        ).reset_index()
        tm = tm[tm["Total"]>=3]
        tm["NSS"] = ((tm["Pos"]-tm["Neg"])/tm["Total"]*100).round(1)
        fig = px.treemap(tm,path=["Tier","Categoria"],values="Total",color="NSS",
            color_continuous_scale=NSS_SCALE,color_continuous_midpoint=0)
        fig.update_layout(height=550,margin=dict(l=10,r=10,t=10,b=10))
        fig.update_traces(textinfo="label+value")
        return fig

    # ========================================================================

    @render_plotly
    def fig_piramide():
        ds = sent()
        if len(ds) == 0: return go.Figure()
        prof = ds.groupby("Veículo_de_comunicacao").agg(
            Total=("Classificação","count"),
            Positiva=("Classificação",lambda x:(x=="POSITIVA").sum()),
            Negativa=("Classificação",lambda x:(x=="NEGATIVA").sum()),
            Tier_Dom=("Tier",lambda x:x.mode().iloc[0] if len(x.mode())>0 else "Null"),
        ).reset_index()
        prof = prof[prof["Total"]>=input.min_vol()]
        top_neg = prof.nlargest(10,"Negativa")
        top_pos = prof.nlargest(10,"Positiva")
        comb = pd.concat([top_neg,top_pos]).drop_duplicates(subset="Veículo_de_comunicacao")
        comb["NSS"] = ((comb["Positiva"]-comb["Negativa"])/comb["Total"]*100).round(1)
        comb = comb.sort_values("NSS")
        comb["Label"] = comb.apply(lambda r: f"{TIER_EMOJI.get(r['Tier_Dom'],'⚪')} {r['Veículo_de_comunicacao']}", axis=1)
        fig = go.Figure()
        fig.add_trace(go.Bar(y=comb["Label"],x=-comb["Negativa"],orientation="h",name="Negativas",marker_color="#e74c3c",
            text=comb["Negativa"].apply(lambda v:f"{int(v)}" if v>0 else ""),textposition="inside",textfont=dict(color="white")))
        fig.add_trace(go.Bar(y=comb["Label"],x=comb["Positiva"],orientation="h",name="Positivas",marker_color="#2ecc71",
            text=comb["Positiva"].apply(lambda v:f"{int(v)}" if v>0 else ""),textposition="inside",textfont=dict(color="white")))
        fig.add_vline(x=0,line_width=2,line_color="#2c3e50")
        fig.update_layout(height=max(500,len(comb)*32),template="plotly_white",barmode="relative",margin=dict(l=20,r=20,t=10,b=30),
            legend=dict(orientation="h",y=-0.06,x=0.4))
        return fig

    # ========================================================================

    @render_plotly
    def fig_sunburst():
        ds = sent()
        if len(ds) == 0: return go.Figure()
        sun = ds.groupby(["Classificação","Categoria","Subcategoria"]).size().reset_index(name="Total")
        sun = sun[sun["Total"]>=3]
        fig = px.sunburst(sun,path=["Classificação","Categoria","Subcategoria"],values="Total",
            color="Classificação",color_discrete_map=COLORS)
        fig.update_layout(height=600,margin=dict(l=10,r=10,t=10,b=10))
        fig.update_traces(textinfo="label+percent parent",insidetextorientation="radial")
        return fig

    # ========================================================================

    @render_plotly
    def fig_sunburst2():
        ds = sent()
        if len(ds) == 0: return go.Figure()
        ds2 = ds.copy(); ds2["Tier"] = ds2["Tier"].fillna("Null")
        sun = ds2.groupby(["Tier","Categoria","Classificação"]).size().reset_index(name="Total")
        sun = sun[sun["Total"]>=3]
        fig = px.sunburst(sun,path=["Tier","Categoria","Classificação"],values="Total",
            color="Classificação",color_discrete_map=COLORS)
        fig.update_layout(height=600,margin=dict(l=10,r=10,t=10,b=10))
        fig.update_traces(textinfo="label+percent parent",insidetextorientation="radial")
        return fig

    # ========================================================================



    return None


_static_assets = ["dashboard_quarto_files","dashboard_quarto_files/libs/quarto-html/tippy.css","dashboard_quarto_files/libs/quarto-html/quarto-syntax-highlighting.css","dashboard_quarto_files/libs/bootstrap/bootstrap-icons.css","dashboard_quarto_files/libs/bootstrap/bootstrap.min.css","dashboard_quarto_files/libs/quarto-dashboard/datatables.min.css","dashboard_quarto_files/libs/clipboard/clipboard.min.js","dashboard_quarto_files/libs/quarto-html/quarto.js","dashboard_quarto_files/libs/quarto-html/popper.min.js","dashboard_quarto_files/libs/quarto-html/tippy.umd.min.js","dashboard_quarto_files/libs/quarto-html/anchor.min.js","dashboard_quarto_files/libs/bootstrap/bootstrap.min.js","dashboard_quarto_files/libs/quarto-dashboard/quarto-dashboard.js","dashboard_quarto_files/libs/quarto-dashboard/stickythead.js","dashboard_quarto_files/libs/quarto-dashboard/datatables.min.js","dashboard_quarto_files/libs/quarto-dashboard/pdfmake.min.js","dashboard_quarto_files/libs/quarto-dashboard/vfs_fonts.js","dashboard_quarto_files/libs/quarto-dashboard/web-components.js","dashboard_quarto_files/libs/quarto-dashboard/components.js"]
_static_assets = {"/" + sa: Path(__file__).parent / sa for sa in _static_assets}

app = App(
    Path(__file__).parent / "dashboard_quarto.html",
    server,
    static_assets=_static_assets,
)
